/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  console.log("Seeding 4 currently showing movies...");

  // Xóa dữ liệu cũ
  await knex("movies").del();

  // 4 phim đang chiếu
  const movies = [
    {
      title:
        "PHIM ĐIỆN ẢNH DORAEMON: NOBITA VÀ CUỘC PHIÊU LƯU VÀO THẾ GIỚI TRONG TRANH",
      description:
        "Thông qua món bảo bối mới của Doraemon, cả nhóm bạn bước thế giới trong một bức tranh nổi tiếng và bắt gặp cô bạn bí ẩn tên Claire. Với lời mời của Claire, cả nhóm cùng đến thăm vương quốc Artoria, nơi ẩn giấu một viên ngọc quý mang tên Artoria Blue đang ngủ yên. Trên hành trình tìm kiếm viên ngọc, nhóm bạn Doraemon phát hiện một truyền thuyết về sự hủy diệt của thế giới, mà truyền thuyết đó dường như đang sống dậy! Liệu cả nhóm có thể phá hủy lời nguyền này và bảo vệ cả thế giới?",
      director: "Yukiyo Teramoto",
      cast: "Wasabi Mizuta, Megumi Ôhara, Yumi Kakazu, Subaru Kimura, Tomokazu Seki,...",
      genre: "Hoạt Hình, Phiêu Lưu",
      duration_min: 105,
      release_date: new Date("2025-05-23"),
      end_date: new Date("2025-06-15"),
      country: "Nhật Bản",
      age_rating: "P",
      status: "active",
      poster_url: "/public/images/poster-doraemon_TG_tranh.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "PHIM ĐIỆN ẢNH DORAEMON: NOBITA VÀ BẢN GIAO HƯỞNG ĐỊA CẦU",
      description:
        "TÁC PHẨM KỶ NIỆM 90 NĂM FUJIKO F FUJIO Chuẩn bị cho buổi hòa nhạc ở trường, Nobita đang tập thổi sáo - nhạc cụ mà cậu dở tệ. Thích thú trước nốt 'No' lạc quẻ của Nobita, Micca - cô bé bí ẩn đã mời Doraemon, Nobita cùng nhóm bạn đến 'Farre' - Cung điện âm nhạc tọa lạc trên một hành tinh nơi âm nhạc sẽ hóa thành năng lượng",
      director: "Kazuaki Imai",
      cast: "Wasabi Mizuta, Megumi Ôhara, Yumi Kakazu",
      genre: "Hoạt Hình",
      duration_min: 115,
      release_date: new Date("2025-05-24"),
      end_date: new Date("2025-08-01"),
      country: "Nhật Bản",
      age_rating: "P",
      status: "active",
      poster_url: "/public/images/poster-doraemon_BGH.jpg",
      trailer_url: "https://www.youtube.com/watch?v=XYZ678GHI90",
      created_at: new Date("2025-05-01T10:30:00Z"),
      updated_at: new Date(),
    },
    {
      title: "Tiếng Gọi Rừng Sâu",
      description:
        "Từ màn ảnh hoạt hình, câu chuyện cảm động về hành trình khám phá và bảo vệ khu rừng nguyên sinh của cậu bé nhỏ Ella.",
      director: "Bong Joon-ho",
      cast: "Ella Tran, Minh Bùi, Hương Giang",
      genre: "Hoạt hình, Gia đình",
      duration_min: 100,
      release_date: new Date("2025-04-20"),
      end_date: new Date("2025-07-01"),
      country: "Hàn Quốc",
      age_rating: "G",
      status: "active",
      poster_url: "/public/images/poster-sample3.jpg",
      trailer_url: "https://www.youtube.com/watch?v=LMN234OPQ56",
      created_at: new Date("2025-03-15T08:45:00Z"),
      updated_at: new Date(),
    },
    // {
    //   title: "Bóng Ma Đêm Khuya",
    //   description:
    //     "Phim kinh dị-huyền bí, hé lộ những bí mật đen tối trong một ngôi làng hẻo lánh bị bóng ma ám ảnh.",
    //   director: "James Wan",
    //   cast: "Lily Collins, Robert Pattinson, Anya Taylor-Joy",
    //   genre: "Kinh dị, Bí ẩn",
    //   duration_min: 120,
    //   release_date: new Date("2025-06-10"),
    //   end_date: new Date("2025-07-30"),
    //   country: "Anh",
    //   age_rating: "R",
    //   status: "active",
    //   poster_url: "/public/images/default-movie-poster.png",
    //   trailer_url: "https://www.youtube.com/watch?v=QRS345TUV78",
    //   created_at: new Date("2025-05-20T11:15:00Z"),
    //   updated_at: new Date(),
    // },
    {
      title: "PHIM ĐIỆN ẢNH CONAN: DƯ ẢNH CỦA ĐỘC NHÃN",
      description:
        "Trên những ngọn núi tuyết của Nagano, một vụ án bí ẩn đã đưa Conan và các thám tử quay trở lại quá khứ.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 120,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-conan.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "PHIM XÌ TRUM",
      description:
        "Câu chuyện trở lại với ngôi làng Xì Trum, nơi mà mỗi ngày đều là lễ hội. Bỗng một ngày, sự yên bình của ngôi làng bị phá vỡ khi Tí Vua bị bắt cóc một cách bí ẩn bởi hai phù thủy độc ác Gà Mên và Cà Mên.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-xitrum.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "SUPERMAN",
      description:
        "Mùa hè tới đây, Warner Bros. Pictures sẽ mang “Superman” - phim điện ảnh đầu tiên của DC Studios đến các rạp chiếu trên toàn cầu. Với phong cách riêng biệt của mình, James Gunn sẽ khắc họa người hùng huyền thoại trong vũ trụ DC hoàn toàn mới, với sự kết hợp độc đáo của các yếu tố hành động đỉnh cao, hài hước và vô cùng cảm xúc.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-superman.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "THẾ GIỚI KHỦNG LONG: TÁI SINH",
      description:
        "Thế Giới Khủng Long: Tái Sinh lấy bối cảnh 5 năm sau phần phim Thế Giới Khủng Long: Lãnh Địa, môi trường Trái đất đã chứng tỏ phần lớn là không phù hợp với khủng long.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-taisinh.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "TIẾNG ỒN QUỶ DỊ",
      description:
        "Sau khi dọn vào căn hộ mới, hai chị em Joo-Young (Lee Sun-Bin) và Joo-Hee (Han Su-A) liên tục bị quấy nhiễu bởi những tiếng động kỳ quái phát ra từ giữa các tầng – thứ âm thanh âm ỉ, vặn vẹo như thể có ai đó… hoặc thứ gì đó đang sống giữa các bức tường. Rồi một ngày, Joo-Hee biến mất không dấu vết.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-tiengonquydi.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "ĐIỀU ƯỚC CUỐI CÙNG",
      description:
        "Biết mình không còn sống được bao lâu vì căn bệnh ALS, Hoàng tâm sự với hai người bạn thân – Thy và Long – về tâm nguyện cuối cùng: được “mất zin” trước khi chết.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-dieuuoccuocung.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "CON NÍT QUỶ",
      description:
        "20 năm sau thảm kịch Jatijajar, nỗi kinh hoàng mang tên Ummu Sibyan một lần nữa trỗi dậy. Lần này, điểm đến là ngôi làng hẻo lánh Giritirto. ",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-connitquy.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "GA TỬ THẦN",
      description:
        "Bước vào thế giới của Ghost Train, khán giả theo chân Da Gyeong (Joo Hyun Young) – một YouTuber trẻ tuổi đang tuyệt vọng cứu vãn tài khoản đang của mình bằng những câu chuyện kỳ bí. Với khát khao phá kỷ lục lượt xem, cô quyết định khám phá ga tàu điện ngầm Gwanglim – nơi phủ đầy truyền thuyết đô thị và nổi tiếng với hàng loạt vụ mất tích bí ẩn.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-gatuthan.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "ĐÀN CÁ GỖ",
      description:
        "Phim ngắn “Đàn Cá Gỗ” - cùng giải thưởng Phim ngắn xuất sắc nhất tại Cánh Diều Vàng 2024; kể về hành trình của Cường, chàng trai miền biển phải gác lại đam mê âm nhạc để chăm lo cho gia đình.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-dacago.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
    {
      title: "BÍ KÍP LUYỆN RỒNG",
      description:
        "Câu chuyện về một chàng trai trẻ với ước mơ trở thành thợ săn rồng, nhưng định mệnh lại đưa đẩy anh đến tình bạn bất ngờ với một chú rồng.",
      director: "Christopher Nolan",
      cast: "Leonardo DiCaprio, Tom Hardy, Joseph Gordon-Levitt",
      genre: "Hành động, Phiêu lưu",
      duration_min: 100,
      release_date: new Date("2025-05-15"),
      end_date: new Date("2025-07-15"),
      country: "Mỹ",
      age_rating: "PG-13",
      status: "active",
      poster_url: "/public/images/poster-bikipluyenrong.jpg",
      trailer_url: "https://www.youtube.com/watch?v=ABC123DEF45",
      created_at: new Date("2025-04-01T09:00:00Z"),
      updated_at: new Date(),
    },
  ];

  // Chèn vào DB
  await knex("movies").insert(movies);
  console.log(`Đã thêm ${movies.length} phim đang chiếu.`);
};
